vinos/stock/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

urlpatterns = [
    # index
    path('', views.index, name='index'),
    # productos
    path('list/', views.ProductList.as_view(), name='product_list'),
    path('product/<int:pid>/', views.product_detail, name='product_detail'),
    path('product/add/', views.add_product, name='add_product'),
    path('product/select/', views.select_product, name='select_product'),
    path('product/edit/<int:pid>/', views.edit_product, name='edit_product'),
    # registros
    path('record/add/<str:type>/', views.add_record, name='add_record'),
    path('record/edit/<int:pk>/', views.RecordUpdateView.as_view(), name='edit_record'),
    path('record/list/', views.RecordsByTime.as_view(), name='record_list'),
    path('record/list/branch/', views.RecordsForCurrentBranch.as_view(), name='record_list_branch'),
    path('record/list/filter/', views.record_list_filter, name='record_list_filter'),
    # sucursales
    path('branch/select/<str:action>/', views.select_branch, name='select_branch'),
    path('branch/edit/<str:branch_name>/', views.edit_branch, name='edit_branch'),
    path('branch/add/', views.register_branch, name='add_branch'),
    path('branch/list/', views.branch_list, name='branch_list'),
    # empleados
    path('employee/<int:employee_id>/', views.employee_detail, name='employee_detail'),
    path('employee/list/', views.employee_list, name='employee_list'),
    path('employee/list/at/<int:branch_id>', views.employee_at_branch_list, name='employee_list_branch'),
    path('employee/edit/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('employee/toggle/<int:employee_id>/', views.toggle_employee, name='toggle_employee'),
    # inventarios
    path('stock/list/', views.stock_list, name='stock_list'),
    path('stock/list/current/', views.current_branch_stock_list, name='stock_list_curr'),
    path('stock/list/<int:branch_id>/', views.branch_stock_list, name='stock_list_branch'),
    path('branch/stock/edit/<str:branch_name>/', views.edit_branch_stock, name='edit_branch_stock'),
    # utilidades
    path('admin/', views.administrate, name='admin_page'),
    path('product-autocomplete/', views.product_autocomplete, name='product-autocomplete'),
    path('employee-autocomplete/', views.employee_autocomplete, name='employee-autocomplete'),
    path('get_product_stock/<str:branch_name>/<int:product_id>/', views.get_product_stock, name='get_product_stock'),
]

vinos/vinos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from stock import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/', include('stock.urls')),
    path('accounts/register/', views.register_user, name='register'),
    path('accounts/login/', views.login_user, name='login'),
    path('accounts/logout/', views.logout_user, name='logout'),
    path('accounts/inactive/', views.inactive_user, name='inactive_user'),
    path('', lambda request: redirect('stock/', permanent=True)),
]

vinos/stock/models.py
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
import datetime

def validate_positive(value):
    if value <= 0:
        raise ValidationError("El valor debe ser positivo")

class Branch(models.Model):
    name = models.CharField(
        max_length=255, 
        verbose_name="Sucursal",
        unique=True,
        validators=[RegexValidator(r'^\S+', 'Este campo no puede estar vacío.')]
    )
    address = models.CharField(
        max_length=255, 
        verbose_name="Direccion",
        validators=[RegexValidator(r'^\S+', 'Este campo no puede estar vacío.')]
    )
    telephone = models.CharField(
        max_length=100, 
        verbose_name="Telefono",
        validators=[RegexValidator(r'^\+?1?\d{9,15}$', 'Número de teléfono no válido.')]
    )

    def __str__(self):
        return self.name

class Person(models.Model):
    dni = models.IntegerField(
        verbose_name="DNI", 
        unique=True,
        validators=[validate_positive]
    )

    class Meta:
        abstract = True

class Employee(Person):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuario", related_name="employee")
    is_active = models.BooleanField(
        verbose_name="En actividad",
        default=True
    )
    cuil = models.CharField(
        verbose_name="CUIL", 
        unique=True,
        max_length=13,
        validators=[
            RegexValidator(
                regex=r'^\d{2}-\d{7,8}-\d$',
                message='El CUIL debe estar en el formato NN-NNNNNNNN-N'
            )
        ]
    )
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, verbose_name="Sucursal")

    def full_name(self):
        return self.user.get_full_name()

    def __str__(self):
        return f"Empleado: {self.user.get_full_name()} - DNI: {self.dni} - CUIL: {self.cuil} - Sucursal: {self.branch} - En actividad: {'Si' if self.is_active else 'No'}"

class Product(models.Model):
    MALBEC = 'Malbec'
    CABERNET = 'Cabernet'
    MERLOT = 'Merlot'
    CHARDONNAY = 'Chardonnay'
    SYRAH = 'Syrah'
    PINOT_NOIR = 'Pinot Noir'
    SAUVIGNON_BLANC = 'Sauvignon Blanc'
    
    VARIETY_CHOICES = [
        (MALBEC, 'Malbec'),
        (CABERNET, 'Cabernet'),
        (MERLOT, 'Merlot'),
        (CHARDONNAY, 'Chardonnay'),
        (SYRAH, 'Syrah'),
        (PINOT_NOIR, 'Pinot Noir'),
        (SAUVIGNON_BLANC, 'Sauvignon Blanc'),
    ]

    name = models.CharField(
        max_length=100, 
        verbose_name="Nombre"
    )
    variety = models.CharField(
        max_length=20,
        choices=VARIETY_CHOICES,
        verbose_name="Varietal"
    )
    description = models.TextField(
        max_length=500, 
        verbose_name="Descripcion"
    )
    vintage = models.IntegerField(
        verbose_name="Cosecha",
        validators=[MinValueValidator(1900), MaxValueValidator(datetime.date.today().year)]
    )
    branches = models.ManyToManyField(Branch, through='BranchStock', verbose_name="Sucursales")

    def __str__(self):
        return f"Cod.: {self.pk} - {self.name} - {self.variety} {self.vintage}"

class BranchStock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='branch_stocks')
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='branch_stocks')
    stock = models.IntegerField(verbose_name="Stock en Sucursal", default=0)

    def __str__(self):
        return f"Sucursal: {self.branch.name} - Producto: {self.product.name} - Stock: {self.stock}"

class Record(models.Model):
    ENTRY = 'entry'
    EXIT = 'exit'
    TYPE_CHOICES = [
        (ENTRY, 'Entry'),
        (EXIT, 'Exit')
    ]

    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    quantity = models.IntegerField(
        verbose_name="Cantidad",
        validators=[validate_positive]
    )
    typeof = models.CharField(
        max_length=5,
        choices=TYPE_CHOICES,
        verbose_name="Tipo"
    )
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT, verbose_name="Empleado")
    date = models.DateTimeField(verbose_name="Fecha de registro", auto_now_add=True)

    def __str__(self):
        return f"Product: {self.product.name} - Branch: {self.branch.name} - Quantity: {self.quantity} - Type:{self.get_typeof_display()} - Employee: {self.employee.full_name()} - Date: {self.date}"

vinos/stock/forms.py
from .forms_auth import LoginUser, RegisterUser
from .forms_branch import RegisterBranch, SelectBranchForm
from .forms_employee import EditEmployeeForm
from .forms_inventory import BranchStockForm
from .forms_product import AddProductForm, SelectProductForm
from .forms_record import AddRecordForm

vinos/stock/views.py
from django.shortcuts import render

from .views_admin import administrate
from .views_auth import register_user,login_user,logout_user,inactive_user
from .views_branch import branch_list, register_branch, edit_branch, select_branch
from .views_employee import employee_list, employee_at_branch_list, employee_detail, employee_autocomplete, edit_employee, toggle_employee
from .views_inventory import stock_list, branch_stock_list, current_branch_stock_list, get_product_stock, edit_branch_stock
from .views_product import ProductList, product_detail, add_product, edit_product, select_product, product_autocomplete
from .views_record import RecordsForCurrentBranch, RecordsByTime, RecordUpdateView, add_record, record_list_filter

def index(req):
    context = {
        'title': 'Control de stock'
    }

    return render(req, 'pages/index.html', context)

vinos/stock/templates/components/pager.html
{% load custom_tags %}
<div class="pagination animate__animated animate__fadeInUp">
    <span class="step-links">
        {% if pages.has_previous %}
            <a href="?{% param_replace page=1 %}"><i class="fa-solid fa-angles-left"></i> primera</a>
            <a href="?{% param_replace page=pages.previous_page_number %}"><i class="fa-solid fa-chevron-left"></i> anterior</a>
        {% else %}
            <span class="disabled"><i class="fa-solid fa-angles-left"></i> primera</span>
            <span class="disabled"><i class="fa-solid fa-chevron-left"></i> anterior</span>
        {% endif %}

        <span class="current">
            Página {{ pages.number }} de {{ pages.paginator.num_pages }}.
        </span>

        {% if pages.has_next %}
            <a href="?{% param_replace page=pages.next_page_number %}">siguiente <i class="fa-solid fa-chevron-right"></i></a>
            <a href="?{% param_replace page=pages.paginator.num_pages %}">última <i class="fa-solid fa-angles-right"></i></a>
        {% else %}
            <span class="disabled">siguiente <i class="fa-solid fa-chevron-right"></i></span>
            <span class="disabled">última <i class="fa-solid fa-angles-right"></i></span>
        {% endif %}
    </span>
</div>

vinos/stock/templates/forms/add_product.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
    <div class="form-container product-form animate__animated animate__bounceIn">
        <h1><i class="fa-solid fa-wine-bottle"></i> {{ title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
        </form>
        <a href="{% url 'product_list' %}"><i class="fa-solid fa-arrow-rotate-left"></i> Volver a la lista</a>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
        const fields = [
            { id: 'id_name', icon: 'fa-champagne-glasses' },
            { id: 'id_variety', icon: 'fa-bottle-droplet' },
            { id: 'id_description', icon: 'fa-align-left' },
            { id: 'id_vintage', icon: 'fa-calendar-check' }
        ];

        fields.forEach(field => {
            const label = document.querySelector(`label[for="${field.id}"]`);
            if (label) {
            const icon = document.createElement('i');
            icon.className = `fa-solid ${field.icon}`;
            label.insertBefore(icon, label.firstChild);
            icon.style.marginRight = '8px';
            }
        });
        });
    </script>
{% endblock %}

vinos/stock/templates/forms/add_record.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
    <div class="form-container animate__animated animate__bounceIn">
        <h1><i class="fa-solid fa-arrow-right-arrow-left"></i> {{ title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
        </form>
        <a href="{% url 'record_list' %}"><i class="fa-solid fa-rotate-left"></i> Volver a la lista</a>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        $(document).ready(function() {
            $('.product-select').select2({
            ajax: {
                url: '{% url "product-autocomplete" %}',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                return {
                    q: params.term, // search term
                };
                },
                processResults: function (data) {
                return {
                    results: data.results
                };
                },
                cache: true
            },
            language: "es",
            minimumInputLength: 1,
            });
        });
    </script>
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        const fields = [
        { id: 'id_product', icon: 'fa-wine-bottle' },
        { id: 'id_quantity', icon: 'fa-wine-glass' }
        ];

        fields.forEach(field => {
        const label = document.querySelector(`label[for="${field.id}"]`);
        if (label) {
            const icon = document.createElement('i');
            icon.className = `fa-solid ${field.icon}`;
            label.insertBefore(icon, label.firstChild);
            icon.style.marginRight = '8px';
        }
        });
    });
    </script>
{% endblock %}

vinos/stock/templates/forms/login.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}Ingreso{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
  <div class="form-container animate__animated animate__fadeIn">
    <h2><i class="fa-solid fa-address-card"></i> Ingresar al sistema</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit"><i class="fa-solid fa-user-check"></i> Ingresar</button>
    </form>
    <a href="{% url 'register' %}"><i class="fa-solid fa-user-plus"></i> Aún no tengo una cuenta</a>
  </div>
{% endblock %}

{% block extra_js %}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const usernameLabel = document.querySelector('label[for="id_username"]');
      const usernameIcon = document.createElement('i');
      usernameIcon.className = 'fa-solid fa-user';
      usernameLabel.insertBefore(usernameIcon, usernameLabel.firstChild);

      const passwordLabel = document.querySelector('label[for="id_password"]');
      const passwordIcon = document.createElement('i');
      passwordIcon.className = 'fa-solid fa-lock';
      passwordLabel.insertBefore(passwordIcon, passwordLabel.firstChild);

      usernameIcon.style.marginRight = '8px';
      passwordIcon.style.marginRight = '8px';
    });
  </script>
{% endblock %}

vinos/stock/templates/forms/register.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}Registro{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
<div class="form-container animate__animated animate__fadeIn">
    <h2><i class="fa-solid fa-user-pen"></i> Registrarse en el sistema</h2>
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"><i class="fa-solid fa-user-plus"></i> Registrar</button>
    </form>
    <a href="{% url 'login' %}"><i class="fa-solid fa-user-clock"></i> Ya tengo una cuenta</a>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
        const fields = [
            { id: 'id_username', icon: 'fa-user' },
            { id: 'id_email', icon: 'fa-envelope' },
            { id: 'id_password1', icon: 'fa-lock' },
            { id: 'id_password2', icon: 'fa-lock' },
            { id: 'id_first_name', icon: 'fa-user' },
            { id: 'id_last_name', icon: 'fa-user' },
            { id: 'id_dni', icon: 'fa-id-card' },
            { id: 'id_cuil', icon: 'fa-id-badge' },
            { id: 'id_branch', icon: 'fa-building' }
        ];

        fields.forEach(field => {
            const label = document.querySelector(`label[for="${field.id}"]`);
            if (label) {
            const icon = document.createElement('i');
            icon.className = `fa-solid ${field.icon}`;
            label.insertBefore(icon, label.firstChild);
            icon.style.marginRight = '8px';
            }
        });
        });
</script>
{% endblock %}

vinos/stock/templates/forms/register_branch.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
    <div class="form-container animate__animated animate__bounceIn">
        <h1><i class="fa-solid fa-building-circle-arrow-right"></i> {{ title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit"><i class="fa-solid fa-circle-check"></i> {{ submit_btn }}</button>
        </form>
        <a href="{% url 'branch_list' %}"><i class="fa-solid fa-arrow-rotate-left"></i> Volver a la lista</a>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
        const fields = [
            { id: 'id_branch', icon: 'fa-building' },
            { id: 'id_name', icon: 'fa-building' },
            { id: 'id_address', icon: 'fa-location-dot' },
            { id: 'id_area_code', icon: 'fa-book' },
            { id: 'id_phone_number', icon: 'fa-phone' }
        ];

        fields.forEach(field => {
            const label = document.querySelector(`label[for="${field.id}"]`);
            if (label) {
            const icon = document.createElement('i');
            icon.className = `fa-solid ${field.icon}`;
            label.insertBefore(icon, label.firstChild);
            icon.style.marginRight = '8px';
            }
        });
        });
    </script>
{% endblock %}

vinos/stock/templates/forms/register_employee.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
    <div class="form-container product-form animate__animated animate__bounceIn">
        <h1><i class="fa-solid fa-circle-plus"></i> {{ title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
        </form>
        <a href="{% url 'employee_list' %}"><i class="fa-solid fa-rotate-left"></i> Volver a la lista</a>
    </div>
{% endblock %}

{% block extra_js %}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const fields = [
        { id: 'id_first_name', icon: 'fa-user' },
        { id: 'id_last_name', icon: 'fa-user' },
        { id: 'id_email', icon: 'fa-envelope' },
        { id: 'id_dni', icon: 'fa-id-card' },
        { id: 'id_cuil', icon: 'fa-id-badge' },
        { id: 'id_branch', icon: 'fa-building' },
        { id: 'id_is_active', icon: 'fa-user-lock' },
        { id: 'id_group', icon: 'fa-user-group' }
      ];

      fields.forEach(field => {
        const label = document.querySelector(`label[for="${field.id}"]`);
        if (label) {
          const icon = document.createElement('i');
          icon.className = `fa-solid ${field.icon}`;
          label.insertBefore(icon, label.firstChild);
          icon.style.marginRight = '8px';
        }
      });
    });
  </script>
{% endblock %}

vinos/stock/templates/forms/select_product.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/forms.css' %}">
{% endblock %}

{% block main %}
    <div class="form-container animate__animated animate__fadeInDown">
        <h1><i class="fa-solid fa-bolt"></i> {{ title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"><i class="fa-solid fa-pen-to-square"></i> Editar</button>
        </form>
        <a href="{% url 'admin_page' %}"><i class="fa-solid fa-rotate-left"></i> Volver a herramientas administrativas</a>
    </div>
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function() {
        $('.product-select').select2({
            ajax: {
                url: '{% url "product-autocomplete" %}',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        q: params.term, // search term
                    };
                },
                processResults: function (data) {
                    return {
                        results: data.results
                    };
                },
                cache: true
            },
            language: "es",
            minimumInputLength: 1,
            width: '100%'
        });
        {% if branch %}
        $('.product-select').on('change', function() {
            var product_id = $(this).val();
            var branch_name = "{{ branch.name }}";
            var url = '{% url "get_product_stock" 0 0 %}'.replace('0/0', branch_name + '/' + product_id);
            
            if (product_id) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    success: function(data) {
                        $('#id_stock').val(data.stock);
                    },
                    error: function(xhr, status, error) {
                        console.error('Error fetching stock:', error);
                        $('#id_stock').val(0);
                    }
                });
            } else {
                $('#id_stock').val(0);
            }
        });
        {% endif %}
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
    const fields = [
        { id: 'id_product', icon: 'fa-wine-bottle' },
        { id: 'id_stock', icon: 'fa-wine-glass' }
    ];

    fields.forEach(field => {
        const label = document.querySelector(`label[for="${field.id}"]`);
        if (label) {
        const icon = document.createElement('i');
        icon.className = `fa-solid ${field.icon}`;
        label.insertBefore(icon, label.firstChild);
        icon.style.marginRight = '8px';
        }
    });
    });
</script>
{% endblock %}

vinos/stock/templates/pages/admin_page.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{title}}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/styles/admin.css' %}">
{% endblock %}

{% block main %}
    <div class="admin-container animate__animated animate__fadeIn">
        <h1 class="title"><i class="fa-solid fa-screwdriver-wrench"></i> Herramientas Administrativas</h1>
        <div class="admin-links">
            {% for category in admin_links %}
                <div class="admin-item">
                    <h2>{{ category.title }}</h2>
                    <ul>
                    {% for link in category.links %}
                        <li class="animate__animated animate__flipInX">
                            <a href="{{ link.url }}">
                                <i class="{{ link.icon_class }}"></i>
                                {{ link.label }}
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

vinos/stock/templates/pages/base.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ company_name }} - {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'web/pictures/wine_barrel.png' %}" type="image/x-icon">
    {% comment %} CDNs {% endcomment %}
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- Select2 Spanish Language -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/es.js"></script>
    <!-- Font Awesome -->
    <!-- <script src="https://kit.fontawesome.com/d385ce05bf.js" crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

    <link rel="stylesheet" href="{% static 'web/styles/base.css' %}">

    {% block extra_css %}{% endblock %}

</head>
<body>
    <header>
        <h1>
            <a href="{% url 'index' %}">
                {{ company_name }}
            </a>
        </h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li class="{% if request.resolver_match.view_name == 'product_list' %}active{% endif %}">
                        <a href="{% url 'product_list' %}"><i class="fa-solid fa-list"></i> Catalogo</a>
                    </li>
                    <li class="{% if request.resolver_match.view_name == 'record_list_branch' %}active{% endif %}">
                        <a href="{% url 'record_list_branch' %}"><i class="fa-solid fa-book"></i> Registros</a>
                    </li>
                    <li class="{% if request.resolver_match.view_name == 'stock_list_curr' %}active{% endif %}">
                        <a href="{% url 'stock_list_curr' %}"><i class="fa-solid fa-clipboard-list"></i> Inventario</a>
                    </li>
                    {% if user|has_group:"System admins" %}
                        <li class="{% if request.resolver_match.view_name == 'admin_page' %}active{% endif %}">
                            <a href="{% url 'admin_page' %}"><i class="fa-solid fa-gear"></i> Admin.</a>
                        </li>
                    {% elif user|has_group:"Managers" %}
                        <li class="{% if request.resolver_match.view_name == 'admin_page' %}active{% endif %}">
                            <a href="{% url 'admin_page' %}"><i class="fa-solid fa-screwdriver-wrench"></i> Gerente</a>
                        </li>
                    {% elif user|has_group:"Branch managers" %}
                        <li class="{% if request.resolver_match.view_name == 'admin_page' %}active{% endif %}">
                            <a href="{% url 'admin_page' %}"><i class="fa-solid fa-wrench"></i> G. Sucursal</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'logout' %}" class="exit" ><i class="fa-solid fa-right-from-bracket"></i> Salir</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}"><i class="fa-solid fa-user-shield"></i> Ingresar</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
    <footer>
        <p>
            <i class="fa-regular fa-copyright"></i>
            <span>{{ company_name }} {% now "Y" %} - Todos los derechos reservados</span>
            <span>|</span>
            <a href="https://github.com/fmlizarraga/proyecto-django-cac"><i class="fa-brands fa-github"></i></a>
        </p>
    </footer>
{% block extra_js %}{% endblock %}
</body>
</html>

vinos/stock/templates/pages/inactive_user.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
    <div class="container">
        <h1>{{ message }}</h1>
    </div>
{% endblock %}